Repository ignis05/cinnamon-game, pull requests merged in 2019-06, with the labels that each got.

#155 Translucent clickbox
  static/js/classes/Unit.js
Labels: enhancement

#157 Restore lost features
  static/pages/game/game.js
  static/pages/game/main.js
Labels: bug fix

#160 Game minimap camframe
  static/js/classes/Camera.js
  static/pages/game/main.css
  static/pages/game/main.html
  static/pages/game/main.js
  static/pages/game/ui.js
Labels: feature

#162 Fixed turns
  server.js
  static/pages/game/game.js
Labels: bug fix

#164 Movement improvements
  server.js
  static/database/maps.db
  static/js/UnitsDB.js
  static/js/classes/Unit.js
  static/pages/game/game.js
  static/pages/game/socket.js
Labels: bug fix, enhancement, feature

#168 Deselect unit
  static/pages/game/game.js
Labels: enhancement

#170 Spawn zones highlighting and restrictions
  static/database/maps.db
  static/js/classes/Map.js
  static/pages/game/game.js
Labels: feature

#174 [HOTFIX] Sticky camera controls
  static/js/classes/Camera.js
  static/pages/game/main.js
Labels: bug fix

#171 Game minimap units
  static/pages/game/game.js
  static/pages/game/main.css
  static/pages/game/main.html
  static/pages/game/main.js
  static/pages/game/ui.js
Labels: feature

#175 Small fixes and features
  static/pages/game/game.js
Labels: enhancement

#183 Fix models-test
  static/pages/test/models_test/main.js
Labels: bug fix

#182 Better spawn tiles highlighting
  static/pages/game/game.js
Labels: enhancement

#181 Server exception on game end
  server.js
Labels: bug fix

#180 Unit select rework
  static/pages/game/game.js
Labels: bug fix, code cleanup

#176 Game help
  static/pages/game/game.js
  static/pages/game/help.js
  static/pages/game/main.js
Labels: feature

#185 Playable maps
  static/database/maps.db
Labels: enhancement

#184 Combat balancing
  static/js/UnitsDB.js
  static/js/classes/Unit.js
  static/pages/game/game.js
Labels: enhancement

#156 Sprite stats
  server.js
  static/js/classes/Unit.js
  static/pages/game/game.js
  static/pages/game/main.js
  static/pages/game/socket.js
  static/pages/game/ui.js
Labels: feature

#187 Game help v2
  static/pages/game/game.js
  static/pages/game/help.js
  static/pages/game/main.css
  static/pages/game/main.html
  static/pages/game/main.js
  static/pages/game/ui.js
Labels: code cleanup, enhancement

#195 Fixed lobby unit inputs not displaying correctly in chrome
  static/pages/lobby/main.css
Labels: bug fix

#194 UI stat-sprite help, raycasting fix
  static/pages/game/help.js
  static/pages/game/main.css
Labels: bug fix, enhancement

#193 Unit previews, UI fixes
  static/pages/game/ui.js
  static/res/img/thumb_dragon.png
  static/res/img/thumb_overlord.png
  static/res/img/thumb_skeleton.png
  static/res/img/thumb_tiger.png
Labels: bug fix, enhancement

#197 Unit summary card during spawn phase
  static/pages/game/main.css
  static/pages/game/ui.js
Labels: feature
